Permit 7 digit codes.
At least for me, that is required.
However, it still mostly doesn't work because this script has trouble talking to the app that's launched.

diff --git a/bin/ucsf-vpn b/bin/ucsf-vpn
--- a/bin/ucsf-vpn
+++ b/bin/ucsf-vpn
@@ -26,7 +26,7 @@
 ###                   is prompted to enter the token.  Valid values are:
 ###                    - 'push' ("approve and confirm" in Duo app),
 ###                    - 'phone' (receive phone call and "press any key"),
-###                    -  6-digit Duo token (from Duo app), or
+###                    -  6 or 7 digit Duo token (from Duo app), or
 ###                    -  44-letter YubiKey token ("press YubiKey").
 ###
 ###  --gui            Connect to VPN via Pulse Secure GUI (default)
@@ -472,8 +472,8 @@ function is_token_valid() {
         return
     fi
     
-    ## Duo 6-digit token
-    if [[ ${#token} -eq 6 ]] && [[ ${token} =~ ^[0-9]+$ ]]; then
+    ## Duo 6 or 7-digit token
+    if [[ ${#token} -eq 6 || ${#token} -eq 7 ]] && [[ ${token} =~ ^[0-9]+$ ]]; then
         mdebug "Duo token detected"
         echo TRUE
         return
@@ -489,11 +489,11 @@ function prompt_token() {
   
     mdebug "PROMPT: Asking user to enter one-time token:"
     while [ -z "${token}" ]; do
-        printf "Enter 'push', 'phone', 'sms', a 6-digit Duo token, or press your YubiKey: " 1>&2;
+        printf "Enter 'push', 'phone', 'sms', a 6 or 7 digit Duo token, or press your YubiKey: " 1>&2;
         read -r -s token
         token=${token/ /}
         if [[ $(is_token_valid "$token") == FALSE ]]; then
-            printf "\\nERROR: Not a valid token ('phone', 'sms', Duo: 6 digits or 'push', YubiKey: 44 letters)\\n"
+            printf "\\nERROR: Not a valid token ('phone', 'sms', Duo: 6 or 7 digits or 'push', YubiKey: 44 letters)\\n"
             token=
         fi
     done
@@ -839,7 +839,7 @@ while [[ $# -gt 0 ]]; do
         elif [[ ${token} == "false" ]]; then
             mdebug "Will not use 2FA authenatication"
         elif [[ $(is_token_valid "$token") == FALSE ]]; then
-            merror "The token (--token) must be 6 digits (Duo) or 44 letters (YubiKey)"
+            merror "The token (--token) must be 6 or 7 digits (Duo) or 44 letters (YubiKey)"
             exit 1
         fi
     elif test "$1" == "--gui"; then
