ShellCheck fixes + other tweaks

diff --git a/bin/ucsf-vpn b/bin/ucsf-vpn
--- a/bin/ucsf-vpn
+++ b/bin/ucsf-vpn
@@ -86,7 +86,7 @@
 ### * UCSF Managing Your Passwords:
 ###   - https://it.ucsf.edu/services/managing-your-passwords
 ###
-### Version: 6.9.9-9009
+### Version: 6.9.9-9010
 ### Copyright: Henrik Bengtsson (2016-2025)
 ### License: GPL (>= 2.1) [https://www.gnu.org/licenses/gpl.html]
 ### Source: https://github.com/HenrikBengtsson/ucsf-vpn
@@ -579,15 +579,27 @@ function prompt_pwd() {
 # -------------------------------------------------------------------------
 # gplient: The GlobalProtect VPN client
 # -------------------------------------------------------------------------
-function gpclient_version() {
-    local -a res
+function curl_version() {
+    local -a out
 
-    mapfile -t res < <(gpclient --version 2> /dev/null)
+    mapfile -t out < <(curl --version 2> /dev/null)
     # shellcheck disable=SC2181
     if [[ $? -ne 0 ]]; then
         echo "<PLEASE INSTALL>"
     else
-        printf "%s\\n" "${res[@]}" | sed -E 's/^gpclient +//' | sed -E 's/ .*//'
+        printf "%s\\n" "${out[@]}" | grep -E "^curl" | sed -E 's/^curl +//' | sed -E 's/ .*//'
+    fi
+}
+
+function gpclient_version() {
+    local -a out
+
+    mapfile -t out < <(gpclient --version 2> /dev/null)
+    # shellcheck disable=SC2181
+    if [[ $? -ne 0 ]]; then
+        echo "<PLEASE INSTALL>"
+    else
+        printf "%s\\n" "${out[@]}" | sed -E 's/^gpclient +//' | sed -E 's/ .*//'
     fi
 }
 
@@ -687,7 +699,7 @@ function gpclient_start() {
     mdebug "opts: [n=${#opts[@]}] ${opts[*]}"
     mdebug "call: sudo UCSF_VPN_VERSION=$(version) UCSF_VPN_LOGFILE=$(logfile) gpclient ${opts[*]}"
 
-    mnote "Open the Duo Mobile app on your smartphone or tablet to confirm ..."
+    mnote "Open the Duo Mobile app on your smartphone to confirm, unless recently authenticated ..."
 
     minfo "Connecting to VPN server '${server}'"
 
@@ -978,31 +990,18 @@ function gpclient_reconnect() {
 }
 
 
-function curl_version() {
-    local -a res
-
-    mapfile -t res < <(curl --version 2> /dev/null)
-    # shellcheck disable=SC2181
-    if [[ $? -ne 0 ]]; then
-        echo "<PLEASE INSTALL>"
-    else
-        printf "%s\\n" "${res[@]}" | grep -E "^curl" | sed -E 's/^curl +//' | sed -E 's/ .*//'
-    fi
-}
-
-
 # -------------------------------------------------------------------------
 # xdotool: command-line X11 automation tool
 # -------------------------------------------------------------------------
 function xdotool_version() {
-    local -a res
+    local -a out
 
-    mapfile -t res < <(xdotool version 2> /dev/null)
+    mapfile -t out < <(xdotool version 2> /dev/null)
     # shellcheck disable=SC2181
     if [[ $? -ne 0 ]]; then
         echo "<PLEASE INSTALL>"
     else
-        printf "%s\\n" "${res[@]}" | sed -E 's/.* //'
+        printf "%s\\n" "${out[@]}" | sed -E 's/.* //'
     fi
 }
 
@@ -1444,8 +1443,7 @@ elif [[ $action == "routing" ]]; then
     routing_details
     _exit $?
 elif [[ $action == "start" ]]; then
-    gpclient_start
-    res=$?
+    gpclient_start || error "Failed to start VPN client"
     status "connected"
 elif [[ $action == "stop" ]]; then
     gpclient_stop
@@ -1456,8 +1454,7 @@ elif [[ $action == "restart" ]]; then
     if $force || is_connected; then
         gpclient_stop
     fi
-    gpclient_start
-    res=$?
+    gpclient_start || error "Failed to start VPN client"
     status "connected"
 elif [[ $action == "toggle" ]]; then
     if ! is_connected; then
