Now internal connection_details() times out curl query after 3.0 seconds [#40]

diff --git a/bin/ucsf-vpn b/bin/ucsf-vpn
--- a/bin/ucsf-vpn
+++ b/bin/ucsf-vpn
@@ -109,7 +109,7 @@
 ### * UCSF Managing Your Passwords:
 ###   - https://it.ucsf.edu/services/managing-your-passwords
 ###
-### Version: 5.9.9-9014
+### Version: 5.9.9-9015
 ### Copyright: Henrik Bengtsson (2016-2024)
 ### License: GPL (>= 2.1) [https://www.gnu.org/licenses/gpl.html]
 ### Source: https://github.com/HenrikBengtsson/ucsf-vpn
@@ -297,8 +297,10 @@ function connection_details() {
         fi
         minfo "Verified that internet connection works"
         minfo "Getting public IP (from https://ipinfo.io/ip)"
-        mdebug "Calling: curl --silent https://ipinfo.io/json > \"$pii_file\""
-        curl --silent https://ipinfo.io/json > "$pii_file"
+        mdebug "Calling: curl --silent  --connect-timeout 3.0 https://ipinfo.io/json > \"$pii_file\""
+        if ! curl --silent --connect-timeout 3.0 https://ipinfo.io/json > "$pii_file"; then
+            rm "$pii_file"
+        fi
         if [[ ! -f "$pii_file" ]]; then
             merror "Failed to get public IP (from https://ipinfo.io/ip)"
         fi
@@ -383,10 +385,14 @@ function public_info() {
     local ip hostname org
 
     mdebug "public_info()"
-    ip=$(public_ip)
-    hostname=$(public_hostname)
-    org=$(public_org)
-    printf "ip=%s, hostname='%s', org='%s'" "$ip" "$hostname" "$org"
+    ip=$(public_ip 2> /dev/null)
+    if [[ -n "${ip}" ]]; then
+        hostname=$(public_hostname)
+        org=$(public_org)
+        printf "ip=%s, hostname='%s', org='%s'" "$ip" "$hostname" "$org"
+    else
+        printf "<failed to infer information>"
+    fi
 }
 
 function is_online() {
