Add option --skip

diff --git a/bin/ucsf-vpn b/bin/ucsf-vpn
--- a/bin/ucsf-vpn
+++ b/bin/ucsf-vpn
@@ -11,6 +11,8 @@
 ### Options:
 ###  --user         UCSF VPN username
 ###  --pwd          UCSF VPN password
+###  --skip         If already fullfilled, skip command
+###  --force        Force running the command
 ###  --verbose      Verbose output
 ###  --help         This help
 ###  --version      Display version
@@ -77,9 +79,9 @@ function is_connected() {
     mdebug "Public IP: $ip"
     nslookup $ip | grep -q -F "ucsf.edu"
     if [[ $? == 0 ]]; then
-        echo "true"
+        echo TRUE
     else
-        echo "false"
+        echo FALSE
     fi
 }
 function status() {
@@ -99,7 +101,7 @@ function status() {
       mdebug ip=$ip
       mdebug connected=$connected
     fi
-    if [[ $connected == "true" ]]; then
+    if [[ $connected == TRUE ]]; then
         echo "Connected via the UCSF VPN network (your public IP is $ip)"
     else
         echo "Not connected to the UCSF VPN network (your public IP is $ip)"
@@ -107,12 +109,17 @@ function status() {
 }
 
 function start() {
-    if [[ $force == "false" ]]; then
+    if [[ $force == FALSE || $skip == TRUE ]]; then
       ip=$(public_ip)
       connected=$(is_connected $ip)	
-      if [[ $connected = "true" ]]; then
-          echo "ERROR: $(status $connected $ip)"
-          exit 1
+      if [[ $connected = TRUE ]]; then
+          if [[ $skip = TRUE ]]; then
+              echo "SKIPPING: $(status $connected $ip)"
+              exit 0
+	  else
+              echo "ERROR: $(status $connected $ip)"
+              exit 1
+	  fi
       fi
     fi
 
@@ -163,12 +170,17 @@ function start() {
 }
 
 function stop() {
-    if [[ $force == "false" ]]; then
+    if [[ $force == FALSE || $skip == TRUE ]]; then
       ip=$(public_ip)
-      connected=$(is_connected $ip)	
-      if [[ $connected == "false" ]]; then
-          echo "ERROR: $(status $connected $ip)"
-          exit 1
+      connected=$(is_connected $ip)
+      if [[ $connected == FALSE ]]; then
+          if [[ $skip = TRUE ]]; then
+              echo "SKIPPING: $(status $connected $ip)"
+              exit 0
+          else
+              echo "ERROR: $(status $connected $ip)"
+              exit 1
+	  fi
       fi
       mdebug "Public IP (before): $ip"
     fi
@@ -190,6 +202,7 @@ action=help
 
 ## Options    
 force=FALSE
+skip=FALSE
 debug=FALSE
 verbose=FALSE
 dryrun=FALSE
@@ -220,8 +233,10 @@ while [[ $# > 0 ]]; do
     elif test "$1" == "--verbose"; then
         verbose=TRUE
     elif test "$1" == "--force"; then
-        force=TRUE
-    elif test "$1" == "--dry-run"; then
+        force=TRUE 
+    elif test "$1" == "--skip"; then
+        skip=TRUE
+   elif test "$1" == "--dry-run"; then
         dryrun=TRUE
     elif test "$1" == "--user"; then
         shift
@@ -240,6 +255,7 @@ if [[ $debug == TRUE ]]; then
     mdebug "action: $action"
     mdebug "verbose: $verbose"
     mdebug "force: $force"
+    mdebug "skip: $skip"
     mdebug "dryrun: $dryrun"
     mdebug "extras: $extras"
 fi
